# Упрощённый workflow
name: PWD Simple Deploy

on: [push]

jobs:
  instructions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "## Quick Deploy to PWD" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "git clone https://github.com/${{ github.repository }}.git" >> $GITHUB_STEP_SUMMARY
          echo "cd $(basename ${{ github.repository }})" >> $GITHUB_STEP_SUMMARY
          echo "docker-compose up -d" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
